[versions]
androidx-activity = "1.10.1"
androidx-benchmark = "1.3.3"
androidx-core = "1.16.0"
androidx-paging = "3.3.6"
androidx-exifinterface="1.4.1"

binaryCompatibility = "0.17.0"
buildKonfig = "0.17.1"

calf-picker="0.7.1"
coroutines = "1.10.1"
coil3 = "3.2.0"
compose-placeholder = "1.0.11"

dokka = "2.0.0"

gradle-plugin-android = "8.10.0"
gradle-plugin-vanniktech-publish = "0.32.0"

haze = "1.6.0"

kotlinx-atomicfu = "0.27.0"
kotlinx-datetime = "0.6.2"
kotlinx-serialization = "1.8.1"
ktor = "3.1.3"
ksoup = "0.5.0"

jetbrains-compose = "1.8.1"
jetbrains-lifecycle = "2.8.4"

kotlin = "2.1.21"
ktlint = "1.5.0"
ksp = "2.1.21-2.0.1"

room = "2.7.1"

mockk = "1.13.14"
moko = "0.19.1"

spotless = "7.0.3"
sqlite = "2.5.0"
sqldelight = "2.1.0"
uiUnitAndroid = "1.8.0"



[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }

calf-picker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf-picker" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
compose-placeholder = { module = "com.eygraber:compose-placeholder", version.ref = "compose-placeholder" }

gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-plugin-android" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-kotlin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-jetbrains-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
gradlePlugin-vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-plugin-vanniktech-publish" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

jetbrains-compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetbrains-compose" }
jetbrains-lifecycle = { module = "org.jetbrains.androidx.lifecycle:lifecycle-common", version.ref = "jetbrains-lifecycle" }
jetbrains-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle" }

kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-swing = {  module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ksoup-html = { module = "com.mohamedrejeb.ksoup:ksoup-html", version.ref = "ksoup" }
ksoup-entities = { module = "com.mohamedrejeb.ksoup:ksoup-entities", version.ref = "ksoup" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moko-permissions-camera = { module = "dev.icerock.moko:permissions-camera", version.ref = "moko" }
moko-permissions-gallery = { module = "dev.icerock.moko:permissions-gallery", version.ref = "moko" }
moko-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
sqldelight-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-extension-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
androidx-ui-unit-android = { group = "androidx.compose.ui", name = "ui-unit-android", version.ref = "uiUnitAndroid" }

[plugins]
room = { id = "androidx.room", version.ref = "room" }

baselineProfile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
binaryCompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibility" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
